// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoLoadPackageManager
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAutoLoadPackageManagerString = "712bf5cc-618c-43fb-999e-570279df0728";
        public const string guidAutoLoadPackageManagerCmdSetString = "c8228f23-0c49-4b65-9e37-5e1f45a95799";
        public static Guid guidAutoLoadPackageManager = new Guid(guidAutoLoadPackageManagerString);
        public static Guid guidAutoLoadPackageManagerCmdSet = new Guid(guidAutoLoadPackageManagerCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageManagerToolWindowCommandId = 0x0100;
    }
}
